spring:
  application:
    name: employee-service
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/MyDatabase
  boot:
    admin:
      client:
        url: http://localhost:8080


server:
  port: 8081
  #servlet:
  #  context-path: /employee-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

user-properties:
  files:
    - abc
    - def
    - ghi
  user-details:
    nam:
      user-name: user1
      password: pass1
    cemea:
      user-name: user2
      password: pass2